apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: devboard-secrets
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: devboard-vault
  target:
    name: devboard-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        database-url: "postgres://{{ index . \"db-username\" }}:{{ index . \"db-password\" }}@devboard-app-postgres:5432/{{ index . \"db-name\" }}?sslmode=disable"
  data:
    - secretKey: db-username
      remoteRef:
        key: devboard/db
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: db-password
      remoteRef:
        key: devboard/db
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: db-name
      remoteRef:
        key: devboard/db
        property: database
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: jwt-secret
      remoteRef:
        key: devboard/jwt
        property: secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
