apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: devboard-vault
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: admin-user
      remoteRef:
        key: devboard/grafana
        property: adminUser
    - secretKey: admin-password
      remoteRef:
        key: devboard/grafana
        property: adminPassword
