all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    k3s_version: v1.31.4+k3s1

  children:
    k3s_server:
      hosts:
        k3s-server:
          ansible_host: 192.168.40.40

    k3s_agents:
      hosts:
        k3s-agent-1:
          ansible_host: 192.168.40.41
        k3s-agent-2:
          ansible_host: 192.168.40.42
