all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    k3s_version: v1.29.2+k3s1

  children:
    k3s_server:
      hosts:
        server-1:
          ansible_host: 192.168.56.10

    k3s_agents:
      hosts:
        agent-1:
          ansible_host: 192.168.56.11
        agent-2:
          ansible_host: 192.168.56.12
