apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: devboard
type: Opaque
stringData:
  db-username: {{ .Values.secrets.dbUsername | default "devboard" }}
  db-password: {{ .Values.secrets.dbPassword | default "devboard-secret" }}
  database-url: "postgres://{{ .Values.secrets.dbUsername | default "devboard" }}:{{ .Values.secrets.dbPassword | default "devboard-secret" }}@{{ .Release.Name }}-postgres:5432/devboard?sslmode=disable"
  jwt-secret: {{ .Values.secrets.jwtSecret | default "changeme-jwt-secret-minimum-32-chars" }}
