---
# Middleware pour forcer HTTPS au niveau du header pour ArgoCD
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: forwardauth-https
  namespace: argocd
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Port: "443"
      X-Forwarded-Host: "argocd.devboard.local"
---
# Route Traefik pour ArgoCD via HTTPS (port 443)
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.devboard.local`)
      services:
        - name: argocd-server
          port: 443
  tls:
    passthrough: true
