apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: devboard
  labels:
    app: devboard
    component: backend
spec:
  selector:
    app: devboard
    component: backend
  ports:
    - port: 8080
      targetPort: http
      name: http
