apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - backend-deployment.yml
  - backend-service.yml
  - frontend-deployment.yml
  - frontend-service.yml
  - postgres-statefulset.yml
  - ingress.yml
  - hpa.yml
  - network-policies.yml

commonLabels:
  project: devboard
