# Default deny all ingress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: devboard
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
# Frontend: accept from ingress only
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-ingress
  namespace: devboard
spec:
  podSelector:
    matchLabels:
      component: frontend
  ingress:
    - ports:
        - port: 80
---
# Backend: accept from frontend only
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backend-from-frontend
  namespace: devboard
spec:
  podSelector:
    matchLabels:
      component: backend
  ingress:
    - from:
        - podSelector:
            matchLabels:
              component: frontend
      ports:
        - port: 8080
---
# Postgres: accept from backend only
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-postgres-from-backend
  namespace: devboard
spec:
  podSelector:
    matchLabels:
      component: postgres
  ingress:
    - from:
        - podSelector:
            matchLabels:
              component: backend
      ports:
        - port: 5432
